apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-daemonset 
  labels:
    app: fluentd 
spec:
  selector:
    matchLabels:
      app: fluentd 
  template: 
    metadata:
      labels:
        app: fluentd 
    spec:
      containers:
      - name: fluentd
        image: fluent/fluentd:v1.16.3-debian 
        